# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
  - LOCAL_ORG={{ .Env.LOCAL_ORG }}

before:
  hooks:
    # download mods to local cache
    - go mod download
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  header: |
    ## lagoon-sync (v{{.Version}})
    ### Installation via Brew
    The preferred method is installation via [Homebrew](https://brew.sh/).
    ```
    brew tap {{ .Env.LOCAL_ORG }}/lagoon-sync
    brew install lagoon-sync
    ```
    ### Running from released binaries
    Alternatively, you may install by downloading one of the pre-compiled binaries (replace `amd64` with `arm64` for ARM-compatible binaries)
    ```
    # MacOS
    sudo curl -L "https://github.com/{{ .Env.LOCAL_ORG }}/lagoon-sync/releases/download/v{{.Version}}/lagoon-sync_{{.Version}}_darwin_amd64" -o /usr/local/bin/lagoon-sync && sudo chmod +x /usr/local/bin/lagoon-sync
    # Linux
    sudo curl -L "https://github.com/{{ .Env.LOCAL_ORG }}/lagoon-sync/releases/download/v{{.Version}}/lagoon-sync_{{.Version}}_linux_amd64" -o /usr/local/bin/lagoon-sync && sudo chmod +x /usr/local/bin/lagoon-sync
    ```
    ### Running from a Dockerfile
    Alternatively, you may download the latest release as a Dockerfile from [GitHub](https://github.com/{{ .Env.LOCAL_ORG }}/lagoon-sync/pkgs/container/lagoon-sync) or [Docker Hub](https://hub.docker.com/r/{{ .Env.LOCAL_ORG }}/lagoon-sync)
    See the [docs](https://uselagoon.github.io/lagoon-cli/#running_as_a_docker_image) for information on running as a Dockerfile
    ```
    docker pull ghcr.io/{{ .Env.LOCAL_ORG }}/lagoon-sync:v{{.Version}}
    docker pull docker.io/{{ .Env.LOCAL_ORG }}/lagoon-sync:v{{.Version}}
    ```
  # Defaults to empty.
  name_template: "{{.ProjectName}}-v{{.Version}}"

archives:
  - id: binaries
    builds:
    - lagoon
    format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    files:
      - none*
  - id: binaries-targz
    builds:
      - lagoon
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

source:
  enabled: true
  format: 'tar.gz'
  name_template: "{{ .ProjectName }}-v{{ .Version }}-source"

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# signs:
#   - artifacts: checksum
#     args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: lagoon-sync
    tap:
      owner: "{{ .Env.LOCAL_ORG }}"
      name: homebrew-lagoon-sync
    homepage: "https://github.com/{{ .Env.LOCAL_ORG }}/lagoon-sync"
    description: "Lagoon's development sync tool"
    skip_upload: false
    test: system "#{bin}/lagoon-sync version"
    install: bin.install "lagoon-sync"
    ids:
      - binaries-targz